---
title: "p8105_hw5_jdr2191"
output: github_document
---
```{r load_libraries}
library(tidyverse)
library(viridis)
```

## Problem 1

```{r}
homicide_df = 
  read_csv("./homicides/homicide-data.csv", na = c("", "Unknown")) %>%
  mutate(city_state = str_c(city, state),
         resolution = case_when(
           disposition == "Closed without arrest" ~ "unsolved",
           disposition == "Open/No arrest" ~ "unsolved",
           disposition == "Closed by arrest" ~ "solved"
         )) %>%
  relocate(city_state) %>%
  filter(city_state != "TulsaAL")

homicide_df %>%
  count(city_state) %>% view

```

victim_age: encoded as a character (will want to address)
some other things are listed as NA

The homicide dataset contains `r count(homicide_data)` observations.

Let's look at Baltimore, MD
```{r}
baltimore_df = 
  homicide_df %>%
  filter(city_state == "BaltimoreMD")

baltimore_summary = 
  baltimore_df %>%
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  )

baltimore_test = 
  prop.test(
    x = baltimore_summary %>% pull(unsolved),
    n = baltimore_summary %>% pull(n))

baltimore_test %>%
  broom::tidy()
```
64% were not solved; 95% CI of .627 to .663

Let's try to iterate across cities. 

First off, write a function
```{r}
prop_test_function = function(city_df) {
  
  city_summary = 
  city_df %>%
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  )

city_test = 
  prop.test(
    x = city_summary %>% pull(unsolved),
    n = city_summary %>% pull(n))
  
return(city_test)
  
}
```


## Problem 2

```{r}
allfiles_df = 
  list.files(path = "data", pattern = "*.csv")



view(allfiles_df)
```

